//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace House.DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("House.DataAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Server=192.168.1.27;uid=sa;pwd=Aa@1234; Database=WareHouse;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string ConnDeploySql2008 {
            get {
                return ResourceManager.GetString("ConnDeploySql2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=14.23.159.115,9890; uid=hlyprod;pwd=Haoly@20250429;  Database=h_sys;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string HLYSql {
            get {
                return ResourceManager.GetString("HLYSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=120.24.85.90;  uid=odkskeid7633; pwd=Xlcneway65428373*jkl_djs; Database=WareHouse;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string LiveDB {
            get {
                return ResourceManager.GetString("LiveDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=Localhost;uid=odkskeid7633;pwd=Xlcneway65428373*jkl_djs; Database=NewLand;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string NewayDeploySql {
            get {
                return ResourceManager.GetString("NewayDeploySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=14.23.159.115,9890;  uid=HaoData; pwd=Haoly$8629%;; Database=WareHouse;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string shengchan {
            get {
                return ResourceManager.GetString("shengchan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=192.168.3.173;  uid=sa; pwd=0; Database=WareHouse;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=192.168.0.8,9890;  uid=warehouse; pwd=hlyWh~8618!; Database=WareHouse;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string 仓储测试的数据库连接 {
            get {
                return ResourceManager.GetString("仓储测试的数据库连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=120.236.158.136,9890;  uid=HaoData; pwd=Haoly$8629%;; Database=WareHouse;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string 仓储生产的数据库连接 {
            get {
                return ResourceManager.GetString("仓储生产的数据库连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=192.168.6.190;  uid=sa; pwd=0; Database=h_sys;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string 好来运测试数据库连接 {
            get {
                return ResourceManager.GetString("好来运测试数据库连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=120.236.158.136,9890;uid=HaoData;pwd=Haoly$8629%;;Database=h_sys;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string 好来运生产数据库连接 {
            get {
                return ResourceManager.GetString("好来运生产数据库连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=192.168.6.190;  uid=sa; pwd=0; Database=NewLand;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string 新路程测试数据库 {
            get {
                return ResourceManager.GetString("新路程测试数据库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server=Localhost;uid=odkskeid7633;pwd=Xlcneway65428373*jkl_djs; Database=NewLand;min pool size=4;max pool size=500;connection timeout=60 的本地化字符串。
        /// </summary>
        internal static string 新路程生产数据库 {
            get {
                return ResourceManager.GetString("新路程生产数据库", resourceCulture);
            }
        }
    }
}
